### ISSUE TITLE
Sample application is halted on authentication

### ISSUE THREAD

**Issue by dairyo** [KiiPlatform/photocolle-AndroidSDK#6]
Sample application is halted on authentication.

Exception message is followings:

```
authenticate fails
com.kii.sdk.photocolle.ConnectionException: org.apache.http.client.ClientProtocolException
    at com.kii.sdk.photocolle.AuthHiddenActivity$2.run(AuthHiddenActivity.java:229)
    at java.lang.Thread.run(Thread.java:818)
Caused by: org.apache.http.client.ClientProtocolException
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:562)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:658)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:632)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:621)
    at com.kii.sdk.photocolle.AuthHiddenActivity$2.run(AuthHiddenActivity.java:194)
    ... 1 more
Caused by: org.apache.http.auth.MalformedChallengeException: Authentication challenge is empty
    at org.apache.http.impl.auth.RFC2617Scheme.parseChallenge(RFC2617Scheme.java:77)
    at org.apache.http.impl.auth.AuthSchemeBase.processChallenge(AuthSchemeBase.java:116)
    at org.apache.http.impl.auth.BasicScheme.processChallenge(BasicScheme.java:100)
    at org.apache.http.impl.client.DefaultRequestDirector.processChallenges(DefaultRequestDirector.java:1080)
    at org.apache.http.impl.client.DefaultRequestDirector.handleResponse(DefaultRequestDirector.java:977)
    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:487)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
```

**Comment by naoki-akimoto** [comment]
@shinsuke-nara 
エミュレータ(4.4.2、6.0)、Nexus5(6.0)の3種の環境で試してみましたが、いずれもauthenticationは成功しています。
AndroidStudio、コマンドライン(gradlewを使用してbuildAppとinstallDebugタスクを実行)のどちらも成功しています。
詳細な環境と再現手順を記載してください。

**Comment by dairyo** [comment]
@naoki-akimoto 了解しました。では、一旦iOSの方のチェックに移ってください。

**Comment by dairyo** [comment]
現在は起こっていないのでclosesします。
